function ui = createGameStatusGUI()
% Purpose: Create a simple hands-off status window for the board game.
% Input:   none.
% Output:  ui struct containing the GUI handles.

    ui.Fig = uifigure('Name', 'Board Game Status', ...
        'Position', [100 100 700 420]);

    ui.StatusLabel = uilabel(ui.Fig, ...
        'Position', [20 375 650 30], ...
        'FontSize', 16, ...
        'Text', 'Starting...');

    ui.RollLabel = uilabel(ui.Fig, ...
        'Position', [20 335 650 25], ...
        'FontSize', 15, ...
        'Text', 'Roll: -');

    ui.ScenarioTitle = uilabel(ui.Fig, ...
        'Position', [20 300 200 25], ...
        'FontSize', 15, ...
        'Text', 'Scenario');

    ui.ScenarioArea = uitextarea(ui.Fig, ...
        'Position', [20 20 650 275], ...
        'Editable', 'off', ...
        'FontSize', 14, ...
        'Value', {'Scenario will appear here.'});
end