function ui = createGameStatusGUI()
% Purpose: Create GUI for the ECE Land game.
% Input:   none
% Output:  ui struct containing the GUI handles

    ui.Fig = uifigure('Name', 'ECE Land Game Status', ...
        'Position', [100 100 760 470]);

    ui.StatusLabel = uilabel(ui.Fig, ...
        'Position', [20 425 700 28], ...
        'FontSize', 16, ...
        'Text', 'Starting...');

    ui.RollLabel = uilabel(ui.Fig, ...
        'Position', [20 390 220 24], ...
        'FontSize', 15, ...
        'Text', 'Roll: -');

    ui.TileLabel = uilabel(ui.Fig, ...
        'Position', [260 390 220 24], ...
        'FontSize', 15, ...
        'Text', 'Current Tile: -');

    ui.ScenarioTitle = uilabel(ui.Fig, ...
        'Position', [20 355 150 24], ...
        'FontSize', 15, ...
        'Text', 'Scenario');

    ui.ScenarioArea = uitextarea(ui.Fig, ...
        'Position', [20 95 720 255], ...
        'Editable', 'off', ...
        'FontSize', 14, ...
        'Value', {'Scenario will appear here.'});

    ui.RollButton = uibutton(ui.Fig, 'push', ...
        'Position', [20 35 140 42], ...
        'FontSize', 15, ...
        'Text', 'Roll Die');

    ui.DoneLabel = uilabel(ui.Fig, ...
        'Position', [190 38 320 28], ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'Text', '');

    ui.CompleteLampLabel = uilabel(ui.Fig, ...
        'Position', [620 42 95 22], ...
        'Text', 'Complete');

    ui.CompleteLamp = uilamp(ui.Fig, ...
        'Position', [715 40 20 20], ...
        'Color', [0.7 0.7 0.7]);

    ui.Fig.UserData.RollRequested = false;
    
    ui.RollButton.ButtonPushedFcn = @(src,event) setRollFlag();
    
    function setRollFlag()
        data = ui.Fig.UserData;
        data.RollRequested = true;
        ui.Fig.UserData = data;
    end
end